"""add aic_code to medication

Revision ID: 35c329061644
Revises: 6b1b3bd64b02
Create Date: 2025-08-01 16:41:08.365472

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35c329061644'
down_revision = '6b1b3bd64b02'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medication', schema=None) as batch_op:
        batch_op.add_column(sa.Column('aic_code', sa.String(length=64), nullable=True))
        batch_op.create_unique_constraint('uq_medication_aic_code', ['aic_code'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medication', schema=None) as batch_op:
        batch_op.drop_constraint('uq_medication_aic_code', type_='unique')
        batch_op.drop_column('aic_code')

    # ### end Alembic commands ###
